//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alpha
    {
        public long FirstKeyphraseId { get; set; }
        public long SecondKeyphraseId { get; set; }
        public Nullable<float> AlphaValue { get; set; }
    }
}
