//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRelationship
    {
        public ClassRelationship()
        {
            this.Class_ClassRelationship = new HashSet<Class_ClassRelationship>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Class_ClassRelationship> Class_ClassRelationship { get; set; }
    }
}
