//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyphrase_KeyphraseRelationship
    {
        public long SourceId { get; set; }
        public long TargetId { get; set; }
        public long RelationshipId { get; set; }
        public Nullable<float> RelValue { get; set; }
    
        public virtual Keyphrase Keyphrase { get; set; }
        public virtual Keyphrase Keyphrase1 { get; set; }
        public virtual KeyphraseRelationship KeyphraseRelationship { get; set; }
    }
}
