//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateKeyphraseGraphLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyphraseRelationship
    {
        public KeyphraseRelationship()
        {
            this.Betas = new HashSet<Beta>();
            this.Betas1 = new HashSet<Beta>();
            this.Keyphrase_KeyphraseRelationship = new HashSet<Keyphrase_KeyphraseRelationship>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<float> MinValue { get; set; }
        public Nullable<float> MaxValue { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Beta> Betas { get; set; }
        public virtual ICollection<Beta> Betas1 { get; set; }
        public virtual ICollection<Keyphrase_KeyphraseRelationship> Keyphrase_KeyphraseRelationship { get; set; }
    }
}
