//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateKeyphraseGraphLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyphrase
    {
        public Keyphrase()
        {
            this.Keyphrase_KeyphraseClass = new HashSet<Keyphrase_KeyphraseClass>();
            this.Keyphrase_KeyphraseRelationship = new HashSet<Keyphrase_KeyphraseRelationship>();
            this.Keyphrase_KeyphraseRelationship1 = new HashSet<Keyphrase_KeyphraseRelationship>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string MonoKeyphrases { get; set; }
        public string Label { get; set; }
        public string FormOrder { get; set; }
    
        public virtual ICollection<Keyphrase_KeyphraseClass> Keyphrase_KeyphraseClass { get; set; }
        public virtual ICollection<Keyphrase_KeyphraseRelationship> Keyphrase_KeyphraseRelationship { get; set; }
        public virtual ICollection<Keyphrase_KeyphraseRelationship> Keyphrase_KeyphraseRelationship1 { get; set; }
    }
}
