//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateKeyphraseGraphLibrary.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyphraseClass
    {
        public KeyphraseClass()
        {
            this.Class_ClassRelationship = new HashSet<Class_ClassRelationship>();
            this.Class_ClassRelationship1 = new HashSet<Class_ClassRelationship>();
            this.Keyphrase_KeyphraseClass = new HashSet<Keyphrase_KeyphraseClass>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Class_ClassRelationship> Class_ClassRelationship { get; set; }
        public virtual ICollection<Class_ClassRelationship> Class_ClassRelationship1 { get; set; }
        public virtual ICollection<Keyphrase_KeyphraseClass> Keyphrase_KeyphraseClass { get; set; }
    }
}
