CREATE TABLE [dbo].[ArticleKG]
(
	[Id] INT  NOT NULL PRIMARY KEY,
	[LDVL_Graph] NVARCHAR(MAX) NULL, 
	[DT_Graph] NVARCHAR(MAX) NULL,
    CONSTRAINT [FK_ArticleKG_Article] FOREIGN KEY ([Id]) REFERENCES [Article]([Id])
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
