CREATE TABLE [dbo].[SystemMessage]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	[Type] NVARCHAR(50) DEFAULT 'MESSAGE',
	[Time] SMALLDATETIME NOT NULL,
	[UserId] INT NOT NULL,
	[Title] NVARCHAR(200) NULL,
	[Content] NVARCHAR(MAX) NULL,
	[URL] NVARCHAR(200) NULL,
	[IsRead] BIT NOT NULL DEFAULT 'False',
)
