CREATE TABLE [dbo].[UserQuery]
(
	[Id] INT IDENTITY NOT NULL PRIMARY KEY,
	[UserId] INT NOT NULL,
	[Name] NVARCHAR(MAX) NULL,
	[Description] NVARCHAR(MAX) NULL,
	[SearchQuery] NVARCHAR(MAX) NULL,
	[SavedTime] SMALLDATETIME NULL,
	[IsSaved] BIT DEFAULT '0', 
    CONSTRAINT [FK_UserQuery_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
	ON UPDATE CASCADE
	ON DELETE CASCADE,
)
